apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://host.docker.internal:7070
    access: proxy
    isDefault: true

  - name: PostgreSQL
    type: postgres
    url: postgresql:5432
    user: postgresql_user
    secureJsonData:
      password: 'postgresql_password'
    jsonData:
      database: Avancira
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
    isDefault: true

  - name: Loki
    type: loki
    url: http://host.docker.internal:3100
    access: proxy
    isDefault: false
